[package]
name = "lab2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
rand = "0.8"
memmap2 = "0.9"
dbus = "0.9"
dbus-crossroads = "0.5"
